version: "3.7"

services:
  python-diagrams:
    container_name: python-diagrams
    hostname: python-diagrams.local
    build:
      context: .
    working_dir: /src
    volumes:
      - ..:/src:cached
    command: >
      bash -c "sleep infinity"
    networks:
      python-diagrams-net:

networks:
  python-diagrams-net:
